name: Build OpenWrt IPK

on:
#   push:
#     # tags:
#     #   - 'v*' # 当创建版本标签时触发
  workflow_dispatch: # 允许手动触发
    inputs:
      version:
        description: '版本号 (不含v前缀)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, i386, arm_cortex-a5, arm_cortex-a7, arm_cortex-a8, arm_cortex-a9, arm_cortex-a15_neon-vfpv4, aarch64, mips_24kc, mipsel_24kc]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create directory structure
        run: |
          mkdir -p openwrt/build

      - name: Build binary
        run: |
          chmod +x openwrt/scripts/build.sh
          ./openwrt/scripts/build.sh ${{ github.event.inputs.version }}

      - name: Package IPK
        run: |
          chmod +x openwrt/scripts/package-openwrt.sh
          ./openwrt/scripts/package-openwrt.sh ${{ github.event.inputs.version }} ${{ matrix.arch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloud-clipboard-${{ github.event.inputs.version }}-${{ matrix.arch }}
          path: openwrt/build/cloud-clipboard-${{ github.event.inputs.version }}-${{ matrix.arch }}

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloud-clipboard_${{ github.event.inputs.version }}_${{ matrix.arch }}.ipk
          path: openwrt/build/cloud-clipboard_${{ github.event.inputs.version }}_${{ matrix.arch }}.ipk

  build-luci:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory structure
        run: |
          mkdir -p openwrt/build
          # 设置权限，递归为所有文件增加可执行权限
          find openwrt/luci-app-cloud-clipboard -type f -exec chmod +x {} \;
      
      - name: Package LuCI App
        run: |
          chmod +x openwrt/scripts/package-luci-app.sh
          ./openwrt/scripts/package-luci-app.sh ${{ github.event.inputs.version }}
      
      - name: Upload LuCI IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-cloud-clipboard_${{ github.event.inputs.version }}_all.ipk
          path: openwrt/build/luci-app-cloud-clipboard_${{ github.event.inputs.version }}_all.ipk

  release:
    needs: [build, build-luci]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.ipk
            artifacts/**/cloud-clipboard-*
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          tag_name: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || format('v{0}', github.event.inputs.version) }}
          name: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || format('v{0}', github.event.inputs.version) }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}