name: Releaser
on:
  push:
    tags:
      - '*'
  # 添加手动触发选项
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: 'latest'
      push_to_registry:
        description: '是否推送到镜像仓库'
        type: boolean
        required: true
        default: true

permissions:
  contents: write
  packages: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tag
        run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 提取版本号，不带 'v' 前缀
      - name: Extract version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Docker meta (Debian)
        id: meta-debian
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
            type=raw,value=${{ steps.extract_version.outputs.version }}

      # - name: Docker meta (Alpine)
      #   id: meta-alpine
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: |
      #       ghcr.io/${{ github.repository }}
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      #     tags: |
      #       type=ref,event=tag,suffix=-alpine
      #       type=raw,value=latest-alpine

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Alpine)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cloud-clip/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          
      # - name: Build and push (Debian)
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     tags: ${{ steps.meta-debian.outputs.tags }}
      #     labels: ${{ steps.meta-debian.outputs.labels }}
